version: '3.3'
services:
  mysql:
    image: mysql
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_DATABASE=sing_db
      - MYSQL_ROOT_PASSWORD=sing_pwd
      - MYSQL_TCP_PORT=3306
    ports:
      - target: 3306
        published: 3307
        protocol: tcp
        mode: host
    networks:
      - singmanaus
  php:
    build: ./docker-files
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - singmanaus
    volumes:
      - '../src:/var/www/html'
networks:
  singmanaus: null
